name: Build touchHLE

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # touchHLE's git-describe versioning needs tag history
    # Apparently the Windows runner already has clang-format? That's nice.
    - name: Check formatting
      shell: bash # no command output without this
      run: dev-scripts/format.sh --check
    - name: Get Submodules
      run: git submodule update --init
    - name: Try to get cached copy of Boost
      id: cache-boost
      uses: actions/cache@v3
      with:
        path: vendor\boost
        key: boost_1_81_0
    - if: ${{ steps.cache-boost.outputs.cache-hit != 'true' }}
      name: Download Boost
      run: curl -L -o boost_1_81_0.7z "https://archives.boost.io/release/1.81.0/source/boost_1_81_0.7z"
    - if: ${{ steps.cache-boost.outputs.cache-hit != 'true' }}
      name: Extract Boost
      run: 7z -ovendor x boost_1_81_0.7z && ren vendor\boost_1_81_0 boost
    - name: Try to get cached copy of cmake
      id: cache-cmake
      uses: actions/cache@v3
      with:
        path: vendor/cmake
        key: cmake_3_31_6_windows
    - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
      name: Download Cmake
      run: curl -L -O "https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6-windows-x86_64.zip"
    - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
      name: Extract Cmake
      run: 7z -ovendor x "cmake-3.31.6-windows-x86_64.zip" && ren vendor\cmake-3.31.6-windows-x86_64 cmake
    # This is the earliest point at which we can do linting: clippy will end up
    # building dynarmic, which needs Boost, but we don't need LLVM until
    # building tests.
    - name: Try to get cached copy of LLVM
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: tests/llvm
        key: llvm_12_0_1_Windows_x64
    - if: ${{ steps.cache-llvm.outputs.cache-hit != 'true' }}
      name: Download LLVM
      run: curl -L -O "https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/LLVM-12.0.1-win64.exe"
    - if: ${{ steps.cache-llvm.outputs.cache-hit != 'true' }}
      name: Extract LLVM
      run: 7z -otests/llvm x LLVM-12.0.1-win64.exe
    # Windows seems to break the stdout pipe for some reason
    - name: Get copy of common-3.0-sdk
      run: cd ${{ github.workspace }}/tests && curl -L --output ${{ runner.temp }}\sdk.tar.gz https://github.com/touchHLE/common-3.0-sdk/releases/latest/download/common-3.0.sdk-windows-x86_64.tar.gz && tar xzvf ${{ runner.temp }}\sdk.tar.gz
    - name: Test
      run: cargo test
      env:
        CMAKE: ${{ github.workspace }}\vendor\cmake\bin\cmake
    - name: Build
      run: cargo build --release
      env:
        CMAKE: ${{ github.workspace }}\vendor\cmake\bin\cmake
    - name: Create bundle
      shell: bash
      run: cd dev-scripts && ./make-windows-bundle.sh ../target/release/touchHLE.exe && mv touchHLE_windows_bundle/ ..
    - uses: actions/upload-artifact@v4
      with:
        name: touchHLE_Windows_x86_64
        path: touchHLE_windows_bundle/
    - uses: actions/upload-artifact@v4
      with:
        name: TestApp_built_on_Windows
        path: tests/TestApp.app
